apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: miniflux

resources:
  - ./resources/deployment.yaml
  - ./resources/ingress.yaml
  - ./resources/namespace.yaml
  - ./resources/service.yaml
  - ./resources/tls.yaml
