apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opentelemetry-operator

resources:
  - ./resources/namespace.yaml
  - https://github.com/open-telemetry/opentelemetry-operator/releases/download/v0.108.0/opentelemetry-operator.yaml
