apiVersion: v1
kind: Service

metadata:
  name: nodeport

spec:
  selector:
    app.kubernetes.io/instance: opentelemetry-collector.opentelemetry-collector
  type: NodePort
  ipFamilies:
    - IPv4
    - IPv6
  ipFamilyPolicy: RequireDualStack
  ports:
    - appProtocol: grpc
      name: otlp-grpc
      port: 4317
      nodePort: 4317
      protocol: TCP
      targetPort: 4317
    - appProtocol: http
      name: otlp-http
      port: 4318
      nodePort: 4318
      protocol: TCP
      targetPort: 4318
