apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector

metadata:
  name: opentelemetry-collector

spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:
        timeout: 1m

    exporters:
      otlp/mackerel:
        endpoint: otlp.mackerelio.com:4317
        compression: gzip
        headers:
          Mackerel-Api-Key: ${env:MACKEREL_APIKEY}

      otlphttp/vaxila:
        endpoint: https://otlp-vaxila.mackerelio.com
        headers:
          Accept: "*/*"
          Mackerel-Api-Key: ${env:VAXILA_APIKEY}

    service:
      telemetry:
        metrics:
          address: :18888
          level: detailed

      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/mackerel]

        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp/vaxila]
  managementState: managed
  envFrom:
    - secretRef:
        name: mackerel-apikey
    - secretRef:
        name: vaxila-apikey
  ipFamilies:
    - IPv4
    - IPv6
  ipFamilyPolicy: RequireDualStack
