apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector

metadata:
  name: opentelemetry-collector

spec:
  config:
    receivers:
      haproxy:
        endpoint: http://haproxy-kubernetes-ingress.haproxy-controller.svc.materia-cluster.ggrel.net:1024/stats
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      podman_stats:
        endpoint: unix://run/podman/podman.sock
      prometheus:
        config:
          scrape_configs:
            - job_name: apcupsd-exporter
              static_configs:
                - targets:
                    - service.apcupsd-exporter.svc.materia-cluster.ggrel.net:9162

    processors:
      batch:
        timeout: 1m

    exporters:
      debug:
        verbosity: detailed
      otlp/mackerel:
        endpoint: otlp.mackerelio.com:4317
        compression: gzip
        headers:
          Mackerel-Api-Key: ${env:MACKEREL_APIKEY}
      otlphttp/vaxila:
        endpoint: https://otlp-vaxila.mackerelio.com
        headers:
          Accept: "*/*"
          Mackerel-Api-Key: ${env:VAXILA_APIKEY}
      prometheusremotewrite:
        endpoint: http://service.prometheus.svc.materia-cluster.ggrel.net:9090/api/v1/write

    service:
      telemetry:
        metrics:
          address: :18888
          level: detailed
      pipelines:
        metrics:
          receivers:
            - haproxy
            - otlp
            - podman_stats
            - prometheus
          processors: [batch]
          exporters: [otlp/mackerel, prometheusremotewrite]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp/vaxila]
  managementState: managed
  envFrom:
    - secretRef:
        name: mackerel-apikey
    - secretRef:
        name: vaxila-apikey
  image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.109.0
  ipFamilies:
    - IPv4
    - IPv6
  ipFamilyPolicy: RequireDualStack
  volumeMounts:
    - name: podman-socket
      mountPath: /run/podman/podman.sock
  volumes:
    - name: podman-socket
      hostPath:
        path: /run/podman/podman.sock
        type: Socket
