apiVersion: v1
kind: Service

metadata:
  name: statsd

spec:
  selector:
    app.kubernetes.io/instance: opentelemetry-collector.opentelemetry-collector
  type: ClusterIP
  ipFamilies:
    - IPv4
    - IPv6
  ipFamilyPolicy: RequireDualStack
  ports:
    - name: statsd
      port: 8125
      targetPort: 8125
