cluster:
  name: materia-cluster
hubble:
  peerService:
    clusterDomain: materia.ggrel.net
  relay:
    enabled: true
  ui:
    enabled: true
    ingress:
      annotations:
        haproxy.org/ssl-redirect: "true"
        haproxy.org/ssl-passthrough: "true"
      enabled: true
      className: haproxy
      hosts: [""]
      paths:
        - /hubble
    baseUrl: /hubble/
ipam:
  operator:
    clusterPoolIPv4MaskSize: 24
    clusterPoolIPv4PodCIDRList:
      - 10.244.0.0/16
    clusterPoolIPv6MaskSize: 120
    clusterPoolIPv6PodCIDRList:
      - fd00::/108
ipv4:
  enabled: true
ipv6:
  enabled: true
k8sServiceHost: boron.dns.ggrel.net
k8sServicePort: 6443
kubeProxyReplacement: true
operator:
  replicas: 1
rollOutCiliumPods: true
routingMode: tunnel
serviceAccounts:
  cilium:
    name: cilium
  operator:
    name: cilium-operator
tunnelProtocol: vxlan
