apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: switchbot-meter-exporter

resources:
  - ./resources/deployment.yaml
  - ./resources/namespace.yaml
  - ./resources/service.yaml
  - ./resources/switchbot-token.yaml
