apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: haproxy-controller

resources:
  - ./resources/ingress-class.yaml
  - ./resources/materia-ggrel-net-certificate.yaml
  - https://raw.githubusercontent.com/haproxytech/kubernetes-ingress/v3.0.2/deploy/haproxy-ingress.yaml

patches:
  - path: ./patches/haproxy-ingress-cm.yaml
  - path: ./patches/service.yaml

images:
  - name: haproxytech/kubernetes-ingress
    newTag: 3.0.2
