apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
spec:
  destination:
    name: ""
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: ingress-nginx
    helm:
      values: |
        controller:
          service:
            ipFamilies:
              - IPv4
              - IPv6
            ipFamilyPolicy: RequireDualStack
            type: NodePort
            nodePorts:
              http: 31080
              https: 31443
    path: ""
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.11.2
  sources: []
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
