apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mastodon

resources:
  - ./resources/deployment.yaml
  - ./resources/ingress.yaml
  - ./resources/mastodon-secrets.yaml
  - ./resources/namespace.yaml
  - ./resources/service.yaml
  - ./resources/tls.yaml

configMapGenerator:
  - name: config
    envs:
      - ./config/config.env
