apiVersion: v1
kind: Service

metadata:
  name: mastodon-streaming
  annotations:
    haproxy.org/backend-config-snippet: |
      timeout http-keep-alive 70s

spec:
  selector:
    app: streaming
  type: ClusterIP
  ipFamilies:
    - IPv4
    - IPv6
  ipFamilyPolicy: RequireDualStack
  ports:
    - name: http
      port: 4000
      targetPort: 4000
