apiVersion: v1
kind: ConfigMap

metadata:
  name: argocd-cm

data:
  kustomize.buildOptions: --enable-helm --load-restrictor LoadRestrictionsNone
  resource.customizations: |
    networking.k8s.io/Ingress:
      health.lua: |
        hs = {}
        hs.status = "Healthy"
        hs.message = "Probably just fine"
        return hs
