apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: argocd-server-http-ingress
  namespace: argocd
  annotations:
    haproxy.org/ssl-redirect: "true"

spec:
  ingressClassName: haproxy
  rules:
    - host: argocd.materia.ggrel.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  name: http

---
apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: argocd-server-grpc-ingress
  namespace: argocd

spec:
  ingressClassName: haproxy
  rules:
    - host: argocd.materia.ggrel.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  name: https
