apiVersion: argoproj.io/v1alpha1
kind: AppProject

metadata:
  name: applications
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - namespace: "*"
      server: "*"
  orphanedResources:
    warn: false
  sourceRepos:
    - "*"
