apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres

resources:
  - ./resources/deployment.yaml
  - ./resources/namespace.yaml
  - ./resources/persistent-volume-claim.yaml
  - ./resources/postgres-password.yaml
  - ./resources/service.yaml
