apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: ingress

spec:
  ingressClassName: haproxy
  tls:
    - secretName: rokoucha-net-tls
      hosts:
        - dot.rokoucha.net
  rules:
    - host: dot.rokoucha.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service
                port:
                  number: 80
