apiVersion: networking.k8s.io/v1
kind: NetworkPolicy

metadata:
  name: argocd-redis-network-policy

spec:
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: grafana
        - namespaceSelector:
            matchLabels:
              name: opentelemetry-collector
  podSelector:
    matchLabels:
      app.kubernetes.io/name: argocd-redis
