apiVersion: cert-manager.io/v1
kind: ClusterIssuer

metadata:
  name: letsencrypt-issuer

spec:
  acme:
    email: ahdrjn65@8c7042.org
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
