apiVersion: v1
kind: Secret

metadata:
  name: tls
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: haproxy-controller/ggrel-net-tls
    cert-manager.io/common-name: ggrel.net

type: kubernetes.io/tls

data:
  tls.key: ""
  tls.crt: ""
