apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ./resources/namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.12.3/manifests/install.yaml

patches:
  - path: ./patches/argo-cd-cm.yaml
