apiVersion: v1
kind: Service

metadata:
  name: service

spec:
  selector:
    app: default
  type: NodePort
  ipFamilies:
    - IPv4
    - IPv6
  ipFamilyPolicy: RequireDualStack
  ports:
    - name: influxdb
      port: 8086
      targetPort: 8086
      nodePort: 8086
