apiVersion: storage.k8s.io/v1
kind: StorageClass

metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  name: beryllium-iscsi

provisioner: csi.san.synology.com
parameters:
  fsType: btrfs
  dsm: "172.16.2.17"
  location: /volume1
  formatOptions: --nodiscard
reclaimPolicy: Delete
allowVolumeExpansion: true
