kind: DaemonSet
apiVersion: apps/v1

metadata:
  name: synology-csi-node
  namespace: synology-csi

spec:
  selector:
    matchLabels:
      app: synology-csi-node
  template:
    spec:
      containers:
        - name: csi-driver-registrar
          env:
            - name: REGISTRATION_PATH
              value: /var/lib/k0s/kubelet/plugins/csi.san.synology.com/csi.sock
        - name: csi-plugin
          volumeMounts:
            - name: kubelet-dir
              mountPath: /var/lib/k0s/kubelet
              mountPropagation: Bidirectional
      volumes:
        - name: kubelet-dir
          hostPath:
            path: /var/lib/k0s/kubelet
            type: Directory
        - name: plugin-dir
          hostPath:
            path: /var/lib/k0s/kubelet/plugins/csi.san.synology.com/
            type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: /var/lib/k0s/kubelet/plugins_registry
            type: Directory
