apiVersion: v1
kind: Service

metadata:
  name: service

spec:
  selector:
    app: default
  type: ClusterIP
  ipFamilies:
    - IPv4
    - IPv6
  ipFamilyPolicy: RequireDualStack
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
