apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: ingress

spec:
  ingressClassName: haproxy
  tls:
    - secretName: tls
      hosts:
        - monitor.ggrel.net
  rules:
    - host: monitor.ggrel.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service
                port:
                  number: 3000
