apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ./resources/argocd-cm.yaml
  - ./resources/argocd-cmd-params-cm.yaml
  - ./resources/ingress.yaml
  - ./resources/namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.12.3/manifests/install.yaml
